// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using keep.Models;

namespace keep.Migrations
{
    [DbContext(typeof(keepContext))]
    [Migration("20180806173241_fifth")]
    partial class fifth
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("keep.Models.CheckList", b =>
                {
                    b.Property<int>("CheckListID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CheckListText");

                    b.Property<int?>("NoteID");

                    b.HasKey("CheckListID");

                    b.HasIndex("NoteID");

                    b.ToTable("CheckList");
                });

            modelBuilder.Entity("keep.Models.Label", b =>
                {
                    b.Property<int>("LabelID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("LabelText");

                    b.Property<int?>("NoteID");

                    b.HasKey("LabelID");

                    b.HasIndex("NoteID");

                    b.ToTable("Label");
                });

            modelBuilder.Entity("keep.Models.Note", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("PinnedStatus");

                    b.Property<string>("PlainText");

                    b.Property<string>("Title")
                        .IsRequired();

                    b.HasKey("ID");

                    b.ToTable("Note");
                });

            modelBuilder.Entity("keep.Models.CheckList", b =>
                {
                    b.HasOne("keep.Models.Note")
                        .WithMany("ChkList")
                        .HasForeignKey("NoteID");
                });

            modelBuilder.Entity("keep.Models.Label", b =>
                {
                    b.HasOne("keep.Models.Note")
                        .WithMany("Label")
                        .HasForeignKey("NoteID");
                });
#pragma warning restore 612, 618
        }
    }
}
