version: "3"
services:
    web:
        build: keep/
        ports:
            - "8001:80"
        depends_on:
            - db
    db:
        image: "microsoft/mssql-server-linux"
        environment:
            SA_PASSWORD: "V_sai1995"
            ACCEPT_EULA: "Y"
