version: '3.4'

services:
  web:
    image: ${DOCKER_REGISTRY}keep_web
    build:
      context: .
      dockerfile: Dockerfile
    ports:
        - "5000:80"
    depends_on:
            - db
  db:
    image: "microsoft/mssql-server-linux"
    environment:
        SA_PASSWORD: "Shashi_1996"
        ACCEPT_EULA: "Y"

        
       