version : '3'
services:
   web:
    build : .
    ports :
       - "8001:80"
     depends_on :
       - db

    db :
      image : "microsoft/mssql-server-linux"
      environmet:
           SA_PASSWORD: "V_sai1995"
           ACCEPT_EULA: "Y"
        
       