version : "3"

services:
   web:
      build : .
      image : keep_web
      ports :
         - "8001:80"
      depends_on :
         - db

   db :
      image : "microsoft/mssql-server-linux"
      environment:
         SA_PASSWORD: "Password"
         ACCEPT_EULA: "Y"
        
       